# Generated by Django 6.1.1 on 2026-09-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carwash',
            options={'verbose_name': 'Car wash', 'verbose_name_plural': 'Car washes'},
        ),
    ]
