# Generated by Django 6.1.1 on 2026-09-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washes', '0002_alter_carwash_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='billing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='carwash',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
