# Generated by Django 6.1.1 on 2026-09-17 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washes', '0003_carwash_billing_status_carwash_monthly_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_year', models.PositiveIntegerField()),
                ('billing_month', models.PositiveSmallIntegerField()),
                ('payment_method', models.CharField(choices=[('eft', 'EFT'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], default='eft', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_payments', to='washes.carwash')),
            ],
        ),
    ]
