# Generated by Django 6.1.1 on 2026-09-18 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washes', '0004_platformpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='washjob',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='washjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='washjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CarWashPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('washer', 'Washer'), ('interior', 'Interior Cleaner'), ('dryer', 'Dryer / Finisher'), ('polisher', 'Polisher'), ('supervisor', 'Supervisor'), ('cashier', 'Cashier'), ('other', 'Other')], default='washer', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='washes.carwash')),
            ],
            options={
                'verbose_name': 'Car wash personnel',
                'verbose_name_plural': 'Car wash personnel',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='washjob',
            name='assigned_personnel',
            field=models.ManyToManyField(blank=True, related_name='wash_jobs', to='washes.carwashpersonnel'),
        ),
        migrations.CreateModel(
            name='WashServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_prices', to='washes.washservice')),
            ],
            options={
                'ordering': ['service', 'vehicle_size'],
                'unique_together': {('service', 'vehicle_size')},
            },
        ),
    ]
