# Generated by Django 6.1.1 on 2026-09-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washes', '0006_seed_the_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='washserviceprice',
            name='quote_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('bakkie_s_cab', 'Bakkie S/Cab'), ('bakkie_d_cab', 'Bakkie D/Cab'), ('combi', 'Combi'), ('14_seater', '14 Seater'), ('bigger', 'Bigger')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='washserviceprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='washserviceprice',
            name='vehicle_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('bakkie_s_cab', 'Bakkie S/Cab'), ('bakkie_d_cab', 'Bakkie D/Cab'), ('combi', 'Combi'), ('14_seater', '14 Seater'), ('bigger', 'Bigger')], max_length=20),
        ),
    ]
