# Generated by Django 6.0.3 on 2026-09-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washes', '0007_washserviceprice_quote_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('bakkie_s_cab', 'Bakkie S/Cab'), ('bakkie_d_cab', 'Bakkie D/Cab'), ('combi', 'Combi'), ('14_seater', '14 Seater'), ('bigger', 'Bigger'), ('mini_suv', 'Mini SUV'), ('mpv', 'MPV'), ('taxi', 'Taxi'), ('bike', 'Bike'), ('trailer', 'Trailer')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='washserviceprice',
            name='vehicle_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('bakkie_s_cab', 'Bakkie S/Cab'), ('bakkie_d_cab', 'Bakkie D/Cab'), ('combi', 'Combi'), ('14_seater', '14 Seater'), ('bigger', 'Bigger'), ('mini_suv', 'Mini SUV'), ('mpv', 'MPV'), ('taxi', 'Taxi'), ('bike', 'Bike'), ('trailer', 'Trailer')], max_length=20),
        ),
    ]
